services:
    ongr_translations.translation_manager:
        class: ONGR\TranslationsBundle\Service\TranslationManager
        arguments:
            - "@ongr_translations.repository.translation"
            - "@ongr_translations.history_manager"
            - "@event_dispatcher"

    ongr_translations.history_manager:
        class: ONGR\TranslationsBundle\Service\HistoryManager
        arguments:
            - "@ongr_translations.repository.translation"

    ongr_translations.import:
        class: ONGR\TranslationsBundle\Service\Import\ImportManager
        arguments:
            - "@ongr_translations.repository.translation"
            - "%kernel.root_dir%"
        calls:
            - ["setLocales", ["%ongr_translations.locales%"]]

    ongr_translations.export:
        class: ONGR\TranslationsBundle\Service\Export\ExportManager
        arguments:
            - "@ongr_translations.translation_manager"
            - "@ongr_translations.export.yaml"
        calls:
            - ["setLocales", ["%ongr_translations.locales%"]]

    ongr_translations.export.yaml:
        class: ONGR\TranslationsBundle\Service\Export\YmlExport
